YouTubeHelper/main/urls.py
from django.urls import path

from . import views


app_name = 'main'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('results/', views.ResultsView.as_view(), name='results'),
    path('liked/', views.LikedView.as_view(), name='liked'),
    path('watch/', views.WatchView.as_view(), name='watch'),
]

YouTubeHelper/project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls'), name='users'),
    path('', include('main.urls'), name='main'),
]

handler404 = 'main.views.error_404'

YouTubeHelper/users/urls.py
from django.urls import path

from . import views


app_name = 'users'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
]

YouTubeHelper/main/models.py
from django.db import models
from django.contrib.auth import get_user_model


UserModel = get_user_model()


class LikedVideos(models.Model):
    user = models.ForeignKey(
        UserModel,
        related_name='liked_videos',
        on_delete=models.CASCADE,
        verbose_name='Пользователь'
    )
    video_id = models.CharField(
        verbose_name='ID Видео',
        max_length=50
    )
    date_time = models.DateTimeField(
        verbose_name='Дата и время',
        auto_now_add=True
    )

    class Meta:
        verbose_name = 'Понравившееся видео'
        verbose_name_plural = 'Понравившиеся видео'
        ordering = ['-date_time']

    def __str__(self):
        return self.video_id


class SearchStory(models.Model):
    query = models.CharField(
        verbose_name='Запрос',
        max_length=300
    )
    date_time = models.DateTimeField(
        verbose_name='Дата и время',
        auto_now_add=True
    )

    class Meta:
        verbose_name = 'Поисковый запрос'
        verbose_name_plural = 'История поиска'
        ordering = ['-date_time']

    def __str__(self):
        return self.query


class SearchCache(models.Model):
    query = models.ForeignKey(
        SearchStory,
        related_name='search_cache',
        on_delete=models.CASCADE,
        verbose_name='Запрос'
    )
    video_id = models.CharField(
        verbose_name='ID Видео',
        max_length=50
    )
    video_title = models.CharField(
        verbose_name='Название',
        max_length=300
    )
    video_short_description = models.CharField(
        verbose_name='Краткое описание',
        max_length=300
    )
    video_channel_title = models.CharField(
        verbose_name='Название канала',
        max_length=150
    )
    video_channel_id = models.CharField(
        verbose_name='ID Канала',
        max_length=50
    )
    video_preview_url = models.CharField(
        verbose_name='URL картинки',
        max_length=300
    )

    class Meta:
        verbose_name = 'Кэш поиска'
        verbose_name_plural = 'Кэш поиска'

YouTubeHelper/users/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass

YouTubeHelper/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class LoginForm(forms.Form):
    username = forms.CharField(
        label='Имя пользователя',
        required=True,
        max_length=150
    )
    password = forms.CharField(
        label='Пароль',
        required=True,
        max_length=128,
        widget=forms.PasswordInput()
    )


class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()

YouTubeHelper/main/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views import View

from . import utils


class IndexView(View):
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        return render(request, 'main/index.html')


class ResultsView(View):
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        context = utils.VideoManager().find_videos(request)
        return render(request, 'main/results.html', context)


class WatchView(View):
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        context = utils.VideoManager().get_video_details(request)
        return render(request, 'main/watch.html', context)


class LikedView(View):
    http_method_names = ['get', 'post']

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('users:login')

        context = utils.VideoManager().get_user_liked_videos(request.user)
        return render(request, 'main/liked.html', context)

    def post(self, request, *args, **kwargs):
        context = utils.VideoManager().get_action_by_like_or_dislike(request)
        return JsonResponse(context)


def error_404(request, exception):
    return render(request, 'main/404.html')

YouTubeHelper/users/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import logout, authenticate, login

from .forms import LoginForm, RegisterForm


class LogoutView(View):
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('main:index')


class LoginView(View):
    http_method_names = ['get', 'post']

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('main:index')

        context = {
            'form': LoginForm()
        }

        return render(request, 'users/login.html', context)

    def post(self, request, *args, **kwargs):
        context = self.authorize_or_get_error(request)

        if request.user.is_authenticated:
            return redirect('main:index')
        else:
            return render(request, 'users/login.html', context)

    def authorize_or_get_error(self, request):
        data = {}

        form = LoginForm(request.POST)

        if form.is_valid():
            cd = form.cleaned_data

            user = authenticate(
                username=cd['username'],
                password=cd['password']
            )

            if user is not None:
                login(request, user)
                return data
            else:
                data['error'] = 'Введен неправильный логин или пароль!'
        else:
            data['error'] = 'Ошибка валидации данных!'

        data['form'] = form
        return data


class RegisterView(View):
    http_method_names = ['get', 'post']

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('main:index')

        return render(request, 'users/register.html', {'form': RegisterForm()})

    def post(self, request, *args, **kwargs):
        form = RegisterForm(request.POST)

        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('main:index')

        return render(request, 'users/register.html', {'form': form})

YouTubeHelper/main/templates/main/index.html
{% extends 'main/layouts/base.html' %}

{% block title %}Главная{% endblock %}

{% block content %}
    <div class="container">
        <div class="search-box">
            <div class="search-logo">
                <a href="https://youtube.com/">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 56 24">
                        <path d="M20.9 19.3h-2.12v-1.24c-.8.94-1.5 1.4-2.23 1.4-.66 0-1.1-.3-1.34-.87-.12-.35-.22-.88-.22-1.67V7.9h2.12V17.16c.05.3.18.42.45.42.4 0 .78-.37 1.23-1V7.9h2.12v11.4M13.4 11.62c0-1.22-.23-2.13-.66-2.7-.56-.8-1.45-1.1-2.35-1.1-1.02 0-1.8.3-2.35 1.1-.44.57-.67 1.5-.67 2.7v4.07c0 1.2.2 2.04.64 2.6.56.8 1.48 1.2 2.37 1.2.9 0 1.82-.4 2.4-1.2.4-.56.6-1.4.6-2.6V11.6zm-2.1 4.3c.1 1.13-.25 1.7-.9 1.7-.66 0-1-.57-.9-1.7V11.4c-.1-1.13.24-1.66.9-1.66.65 0 1 .53.9 1.66v4.52zM5.03 13.1v6.2H2.8v-6.2S.47 5.46 0 4.04h2.35L3.92 10l1.56-5.95h2.34l-2.8 9.04" fill="#111111"/>
                        <path d="M42.74 9.7c-.33 0-.7.2-1.05.52v6.86c.33.34.7.5 1.04.5.6 0 .85-.42.85-1.55v-4.86c0-1.13-.27-1.46-.86-1.46M51.08 11.07c0-1.05-.27-1.36-.94-1.36-.67 0-.96.3-.96 1.35v1.25h1.9v-1.23" fill="#e62117"/>
                        <path d="M55.67 5.28s-.33-2.3-1.33-3.33C53.07.6 51.64.6 51 .53 46.33.2 39.32.2 39.32.2h-.02s-7 0-11.67.33c-.65.08-2.08.08-3.35 1.42-1 1.02-1.32 3.33-1.32 3.33s-.34 2.72-.34 5.44v2.55c0 2.72.34 5.43.34 5.43s.32 2.32 1.32 3.34c1.27 1.34 2.94 1.3 3.68 1.43 2.67.26 11.35.34 11.35.34s7.03 0 11.7-.34c.65-.08 2.07-.08 3.34-1.42 1-1.02 1.33-3.34 1.33-3.34S56 16 56 13.27v-2.55c0-2.72-.33-5.44-.33-5.44zM29.95 19.3h-2.23v-13h-2.35V4.18h7.04V6.3h-2.45v13zm8.05 0h-2.12v-1.24c-.8.94-1.5 1.4-2.23 1.4-.66 0-1.1-.3-1.34-.87-.12-.35-.22-.88-.22-1.67V8h2.12v9.17c.05.3.18.42.45.42.4 0 .78-.37 1.23-1V8H38v11.3zm7.7-3.38c0 1.04-.07 1.78-.2 2.26-.28.84-.87 1.27-1.67 1.27-.72 0-1.46-.44-2.14-1.28v1.14h-2.02V4.18h2V9.1c.66-.8 1.4-1.27 2.15-1.27.8 0 1.34.47 1.6 1.3.15.47.28 1.2.28 2.27v4.52zm4.46 1.67c.5 0 .8-.28.9-.83.02-.1.02-.6.02-1.42h2.12v.32c0 .66-.05 1.13-.07 1.33-.07.46-.23.87-.47 1.23-.56.82-1.4 1.22-2.45 1.22-1.05 0-1.85-.38-2.44-1.16-.43-.57-.7-1.4-.7-2.6v-3.96c0-1.2.25-2.14.68-2.72.58-.77 1.4-1.18 2.42-1.18s1.82.4 2.4 1.18c.4.58.65 1.46.65 2.67V14H49.2v2.02c0 1.05.3 1.57.98 1.57z" fill="#e62117"/>
                    </svg>
                </a>
            </div>
            <div class="search-line">
                <form method="GET" action="{% url 'main:results' %}">
                    <input type="text" class="search-text l-search" name="q" placeholder="Введите запрос">
                    <button type="submit" class="seacrh-submit">
                        <i class="material-icons search-icon">search</i>
                    </button>
                </form>
            </div>
        </div>
        <span class="about-service">Сайт был разработан студентом НУ "ЗП" группы КНТ-117 Маричевым Денисом на основе предоставленого технического задания компанией "Light IT" во время прохождения производственной практики.</span>
    </div>
{% endblock %}

YouTubeHelper/main/templates/main/layouts/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="theme-color" content="#242424">
    <title>MagicEagle | {% block title %}{% endblock %}</title>

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'main/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'main/style.min.css' %}" type="text/css">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
    <header>
        <div class="container">
            <div class="header-wrapper">
                <a href="{% url 'main:index' %}" class="logo">
                    <img src="{% static 'main/logo.png' %}" alt="Logo">
                </a>
                <ul class="navbar">
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'main:liked' %}">Понравившиеся видео</a>
                        </li>
                        <li>
                            <a href="{% url 'users:logout' %}">Выйти</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'users:register' %}">Зарегистрироваться</a>
                        </li>
                        <li>
                            <a href="{% url 'users:login' %}">Войти</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </header>
    <div id="fake-header-area"></div>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <script src="{% static 'main/script.min.js' %}"></script>
</body>
</html>

YouTubeHelper/main/templates/main/layouts/basic.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MagicEagle | {% block title %}{% endblock %}</title>

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'main/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
</head>
<body>
    <header>
        <div class="container">
            <div class="header-wrapper">
                <a href="{% url 'main:index' %}" class="logo">
                    <img src="{% static 'main/logo.png' %}" alt="Logo">
                </a>
                <ul class="navbar">
                    <li>
                        <a href="{% url 'main:liked' %}">Понравившиеся видео</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="">Выйти</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="">Зарегистрироваться</a>
                        </li>
                        <li>
                            <a href="">Авторизироваться</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </header>
    <div id="fake-header-area"></div>

    {% block content %}
    {% endblock %}

    <!-- <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script> -->
    <script src="{% static 'main/script.js' %}"></script>
</body>
</html>

YouTubeHelper/main/templates/main/liked.html
{% extends 'main/layouts/base.html' %}

{% block title %}Понравившиеся видео{% endblock %}

{% block content %}
    <div class="container">
        <div class="block-status b-success visually-hidden">
            <span>Успешно выполнено:</span>
            <ul></ul>
        </div>

        <div class="video-list">
        {% for video in liked_videos %}
            <a class="video-link" href="{% url 'main:watch' %}?v={{ video.video_id }}">
                <div class="video">
                    <div class="video-preview">
                        <img src="{{ video.preview_url }}" alt="Video preview">
                    </div>
                    <div class="video-info">
                        <div class="video-main-info">
                            <div class="video-meta">
                                <div class="video-title">{{ video.title }}</div>
                                <div class="video-channel">{{ video.channel_title }}</div>
                            </div>
                            <div class="video-like">
                                <form class="like-form" onsubmit="d_SubmitHandler(event);">
                                    {% csrf_token %}
                                    <input type="hidden" name="video_id" value="{{ video.video_id }}">
                                    <button type="submit" class="like-button">
                                        <i class="material-icons dislike-icon">favorite</i>
                                    </button>
                                </form>
                            </div>
                        </div>
                        <div class="video-description">{{ video.short_description }}</div>
                    </div>
                </div> 
            </a>
        {% endfor %}
        </div>
    </div>
{% endblock %}

YouTubeHelper/main/templates/main/results.html
{% extends 'main/layouts/base.html' %}

{% block title %}Главная{% endblock %}

{% block content %}
    <div class="container">
        <div class="search-line sl-results">
            <form method="GET">
                <input type="text" name="q" class="search-text m-search" value="{{ q }}" placeholder="Введите запрос">
                <button type="submit" class="seacrh-submit">
                    <i class="material-icons search-icon">search</i>
                </button>
            </form>
        </div>

        <div class="video-list">
        {% for video in videos %}
            <a class="video-link" href="{% url 'main:watch' %}?v={{ video.video_id }}">
                <div class="video">
                    <div class="video-preview">
                        <img src="{{ video.preview_url }}" alt="Video preview">
                    </div>
                    <div class="video-info">
                        <div class="video-main-info">
                            <div class="video-meta">
                                <div class="video-title">{{ video.title }}</div>
                                <div class="video-channel">{{ video.channel_title }}</div>
                            </div>

                            <div class="video-like">
                                <form class="like-form" onsubmit="ld_SubmitHandler(event);">
                                    {% csrf_token %}
                                    <input type="hidden" name="video_id" value="{{ video.video_id }}">
                                    <button type="submit" class="like-button">
                                        {% if video.liked_by_user %}
                                            <i class="material-icons dislike-icon">favorite</i>
                                        {% else %}
                                            <i class="material-icons like-icon">favorite_border</i>
                                        {% endif %}
                                    </button>
                                </form>
                            </div>
                        </div>
                        <div class="video-description">{{ video.short_description }}</div>
                    </div>
                </div> 
            </a>
        {% endfor %}
        </div>
    </div>
{% endblock %}

YouTubeHelper/main/templates/main/watch.html
{% extends 'main/layouts/base.html' %}

{% block title %}Просмотр видео{% endblock %}

{% block content %}
    <div class="container">
        {% if error %}
            <div class="block-status b-errors">
                <span>Ошибки:</span>
                <ul>
                    <li>{{ error }}</li>
                </ul>
            </div>
        {% endif %}

        {% if video %}
            <div class="youtube-video-player">
                <iframe width="1200" height="620" src="https://www.youtube.com/embed/{{ video.video_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>

            <div class="watch-info">
                <div class="w-main">
                    <div class="w-main-info">
                        <div class="w-title">{{ video.title }}</div>
                        <div class="w-channel-publ">
                            <a href="https://www.youtube.com/user/{{ video.channel_id }}" class="w-channel">{{ video.channel_title }}</a>
                            <div class="w-published">({{ video.published_at }})</div>
                        </div>
                    </div>
                    
                    <div class="video-like">
                        <form class="like-form" onsubmit="ld_SubmitHandler(event);">
                            {% csrf_token %}
                            <input type="hidden" name="video_id" value="{{ video.video_id }}">
                            <button type="submit" class="like-button">
                                {% if video.liked_by_user %}
                                    <i class="material-icons dislike-icon">favorite</i>
                                {% else %}
                                    <i class="material-icons like-icon">favorite_border</i>
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>

                <div class="w-additional">
                    <div>
                        <i class="material-icons">access_time</i>
                        <span>{{ video.duration }}</span>
                    </div>
                    {% if video.view_count %}
                        <div>
                            <i class="material-icons">visibility</i>
                            <span>{{ video.view_count }}</span>
                        </div>
                    {% endif %}
                    {% if video.like_count %}
                        <div>
                            <i class="material-icons">thumb_up</i>
                            <span>{{ video.like_count }}</span>
                        </div>
                    {% endif %}
                    {% if video.dislike_count %}
                        <div>
                            <i class="material-icons">thumb_down</i>
                            <span>{{ video.dislike_count }}</span>
                        </div>
                    {% endif %}
                    {% if video.comment_count %}
                        <div>
                            <i class="material-icons">comment</i>
                            <span>{{ video.comment_count }}</span>
                        </div>
                    {% endif %}
                </div>

                <div class="w-description">{{ video.description }}</div>
            </div>
        {% endif %}
    </div>
{% endblock %}

YouTubeHelper/users/templates/users/login.html
{% extends 'main/layouts/base.html' %}

{% block title %}Вход{% endblock %}

{% block content %}
    <div class="container">
        {% if error %}
            <div class="block-status b-errors">
                <span>Ошибки:</span>
                <ul>
                    <li>{{ error }}</li>
                </ul>
            </div>
        {% endif %}
        <div class="card">
            <div class="card-title">Вход</div>
            <div class="card-main">
                <form method="POST">
                    <div class="card-form-container">
                        <div class="card-form-fields">
                            {% csrf_token %}
                            {% for field in form %}
                                {{ field.label_tag }} {{ field }}
                            {% endfor %}
                        </div>
                        <button type="submit" class="card-button">Войти</button>
                    </div>
                </form>
            </div>
            <div class="additionally">У вас еще нет аккаунта? <a href="{% url 'users:register' %}" class="card-link">Зарегистрироваться</a></div>
        </div>
    </div>
{% endblock %}

YouTubeHelper/users/templates/users/register.html
{% extends 'main/layouts/base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}
    <div class="container">
        {% if form.errors %}
            <div class="block-status b-errors">
                <span>Ошибки:</span>
                <ul>
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        <div class="card">
            <div class="card-title">Регистрация</div>
            <div class="card-main">
                <form method="POST">
                    <div class="card-form-container">
                        <div class="card-form-fields">
                            {% csrf_token %}
                            {% for field in form %}
                                {{ field.label_tag }} {{ field }}
                            {% endfor %}
                        </div>
                        <button type="submit" class="card-button">Зарегистрироваться</button>
                    </div>
                </form>
            </div>
            <div class="additionally">Уже есть аккаунт? <a href="{% url 'users:login' %}" class="card-link">Войти</a></div>
        </div>
    </div>
{% endblock %}